[package]
name = "strawberry-chat"
version = "1.11.0-b2"
edition = "2021"
authors = ["Juliandev02", "Paddyk45", "matteodev8"]
description = "A simple but nice chat platform for your terminal"
documentation = "https://developers.strawberryfoundations.xyz/stbchat/introduction"
readme = "README.md"
repository = "https://github.com/Strawberry-Foundations/strawberry-chat"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
stblib = { version =  "0.5.7", features = ["stbchat"] }
# stblib = { version =  "0.5.7", features = ["stbchat"], path = "../stblib-rust" }
tokio = { version = "1.36.0", features = ["full"] }
lazy_static = "1.4.0"
serde = { version = "1.0.197", features = ["derive"] }
serde_yaml = "0.9.32"
serde_json = "1.0.114"
eyre = "0.6.12"
owo-colors = "4.0.0"
futures = "0.3.30"
sqlx = { version = "0.7.3", features = ["mysql", "runtime-tokio-native-tls"] }
sha2 = "0.11.0-pre.3"
hex = "0.4.3"
strip-ansi-escapes = "0.2.0"
chrono = "0.4.34"
reqwest = "0.11.24"
argon2 = "0.5.3"

[profile.release]
opt-level = 'z'
strip = true
lto = true
