[package]
name = "strawberry-chat"
version = "1.11.0-a3"
edition = "2021"
authors = ["Juliandev02", "Paddyk45", "matteodev8"]
description = "A simple but nice chat platform for your terminal"
documentation = "https://developers.strawberryfoundations.xyz/stbchat/introduction"
readme = "README.md"
repository = "https://github.com/Strawberry-Foundations/strawberry-chat"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
stblib = "0.4.1"
tokio = { version = "1.35.1", features = ["full", "io-util"] }
tokio-util = { version = "0.7.10", features = ["io-util"] }
lazy_static = "1.4.0"
serde = { version = "1.0.193", features = ["derive"] }
serde_yaml = "0.9.29"
serde_json = "1.0.108"
eyre = "0.6.11"
owo-colors = "4.0.0"
futures = "0.3.30"
sqlx = { version = "0.7.3", features = ["mysql", "runtime-tokio-native-tls", ] }
sha2 = "0.10.8"
hex = "0.4.3"
strip-ansi-escapes = "0.2.0"

[profile.release]
opt-level = 'z'
strip = true
lto = true
