[package]
name = "strawberry-chat"
version = "1.11.0-a1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
stblib = "0.3.2"
tokio = { version = "1.35.1", features = ["full", "io-util"] }
tokio-util = { version = "0.7.10", features = ["io-util"] }
lazy_static = "1.4.0"
serde = { version = "1.0.193", features = ["derive"] }
serde_yaml = "0.9.29"
serde_json = "1.0.108"
eyre = "0.6.11"
owo-colors = "4.0.0"

[profile.release]
opt-level = 'z'
strip = true
lto = true
