server:
  address: "0.0.0.0"
  port: 8080
  name: "Official Strawberry Chat Server"
  description: "This is the official chat server for Strawberry Chat!"

flags:
  enable_messages: true
  max_message_length: 256
  debug_mode: true
  online_mode: false

config_ver: 2