bot:
  id: 0000-0005
  username: "Strawberry"
  token: "QEAOyPaVCF6o-BJuIOaa0O1ss-psUTSjNyexNu"
  prefix: "!"

server:
  host: "192.168.0.157"
  port: 8080

flags:
  enableUserInput: true
  printReceivedMessagesToTerminal: false