name: Strawberry Chat Binary

on:
   workflow_dispatch:

permissions:
  contents: read

jobs:
  binary-linux:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        pip install nuitka
        
    - name: Build Binary
      run: |
        cd server
        python3 -m nuitka ./server.py --follow-imports --onefile
    
    - name: Move to build directory
      run: |
        mv server.bin build/
    
    - uses: actions/upload-artifact@v3
      with:
        name: strawberry-chat
        path: server/